### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by djciego** [JWally/jsLPSolver#4]
Hi,

I've found your solver, and it's the most clear that I found for my porpouses, but I've detected some strange behaviour and after looking the code for hours I haven't been able to understand where's the problem is...

I need to get a combination of medicaments, given a minimum dose, for the lowest price.
My arrays are as follow:

var arrV = {
	"drug0":
		{"price":"38.11","dosis":75},
	"drug1":
		{"price":"299.83","dosis":750},
	"drug2":
		{"price":"167.58","dosis":300},
	"drug3":
		{"price":"227.49","dosis":450},
	"drug4":
		{"price":"412.43","dosis":900},
	"drug5":
		{"price":"454.70","dosis":1050}};

var arrI = {"drug0":1,"drug1":1,"drug2":1,"drug3":1,"drug4":1,"drug5":1};

The I call solver like this:

solver = new Solver();
	model = {
			"optimize": "price",
			"opType": "min",
			"constraints": {
				"dosis": {"min": minDosis},
			},
			"variables": arrV,
			"ints": arrI
		};
	results = solver.Solve(model);

If for example "minDosis" is 750, I expect to get 1 drug1, and if is 375, 1 drug0 and 1 drug2.
But, let's supose I want a mininum dose of 200. We expect 3 drug0 (114,33 total price), but instead I get 1 drug1 (total price 299,83). If instead of 200 I put a minimum dose of 199 or 201, it works as expected.
I've tried everything, but I cannot find where the bug is...

**Comment by JWally** [comment]
Thanks for the kind words.
Good catch. Should be fixed now.

The solver disqualifies a solution who has a result of less than 0, because
you can't take negative drugs; this makes sense. However, one of the
solutions in the branch-and-bound process was giving a value of -1e-17
(really small) for a solution for one of the drugs. This got kicked out. I
loosened the definition of feasible so that solutions whose results are >
-1e-10 work.

Try now.

**Comment by djciego** [comment]
You've really saved my life. Thank you very much!
