### ISSUE TITLE
SEC types support

### ISSUE THREAD

**Issue by koloff** [JWally/jsLPSolver#58]
Hi and thank you for the amazing work!

Are there any plans for the support of sec types: http://lpsolve.sourceforge.net/5.5/semi-cont.htm.
If not, can you suggest a way to select item 0 or at least "min" times? The item must also have and "max" constraint. 

Thank you!

**Comment by Toffi-123** [comment]
Hi,
does a setup like this help you?
```javascript
model = {
        "optimize": "profit",
        "opType": "max",
        "constraints": {
            "wood": {"max": 300},
            "labor": {"max": 110},
            "storage": {"max": 400},
            "table": {"min": 9, "max": 11},
            "slack": {"max": 1}
        },
        "variables": {
            "table": {"wood": 30,"labor": 5,"profit": 1200,"table": 1, "storage": 30, "slack": 0.0909},
            "dresser": {"wood": 20,"labor": 10,"profit": 1600,"dresser": 1, "storage": 50},
            "slack": {"table": 9, "slack": 1}
        },
        "ints": {"table": 1,"dresser": 1},
        "binaries": {"slack": 1}
   }
```

It would definitely be more elegant to use the big-M method here, but just wanted to ask whether this goes into the direction you were thinking

**Comment by koloff** [comment]
Thank you for the reply, @Toffi-123!

I kind of got the direction of the idea. But after executing the code I get: 
```
{ 
  feasible: true,
  result: 14400,
  dresser: 3,
  slack: 0.09090909,
  table: 8
 }
```

And here, the table value is still less than the table constraint ("table": {"min": 9, "max": 11}). Can you explain the idea and the execution a bit more?
Thanks!

**Comment by Toffi-123** [comment]
That is indeed strange, as the above model should result in the following:

```javascript
{ feasible: true,
  result: 12800,
  bounded: true,
  dresser: 8,
  slack: 1,
  table: -0 }
```

The idea is that the variable "table" may either have values between 9-11, or be 0. In order to let it become 0 we add a "slack" variable that would fulfil our "min/max" requirement of the table variable, in case 0 tables are build. 
The slack variable is introduced as a binary variable, as we either want to completely fulfil our table requirement through the slack variable or not at all.
We are forcing that not both tables and slack are being used by introducing a "slack" constraint, giving it a maximum of 1. If the slack variable receives a value of 1, the "slack" constraint is prohibiting that additional tables are being build. On the other hand, each table adds 1/11 (=0.0909) to the slack variable, making sure that our upper bound on tables remains feasible.

I attached a test file that you can run with Node, hope that helps! If not, could you further explain your setup?

[semCont.js.zip](https://github.com/JWally/jsLPSolver/files/901650/semCont.js.zip)

**Comment by koloff** [comment]
The problem was that the npm version and the version in GitHub are different. Thank you a lot for your help!

**Comment by JWally** [comment]
Sorry for just now getting around to this.
@Toffi-123 : well played!
@koloff : are you good with me closing this?

Thanks!
-JWW
