### ISSUE TITLE
Limit Computation Time

### ISSUE THREAD

**Issue by H4kor** [JWally/jsLPSolver#65]
I've got an IP that takes to long to solve. As I modeled it with gurobi previously I know that it reaches a feasible solutions after a short time and spents most of the time without improving the solution. 
Is it possible to stop the computation early, e.g. after 20 seconds?

**Comment by VotingTool** [comment]
Due to the lack of a timeout, we now changed to the non-commercial [SCIP](http://scip.zib.de/) which is free for academic purposes. It does not have any nice JavaScript / node.js interface, so we have to call it via child_processes, but it offers a bunch of settings including timeouts. Moreover, according to [these](http://plato.asu.edu/ftp/milpc.html) benchmarks, SCIP is one of the fastest non-commercial solvers for mixed integer programs and the included LP solver SoPlex even offers [exact rational solutions](http://soplex.zib.de/doc/html/EXACT.php)!

**Comment by JWally** [comment]
FWIW, I've implemented a timeout for Mixed Integer LPs.
You can incorporate it by updating your model like this:
```
{
    "optimize": "stuff",
    "options": {
        "timeout": 3000,
    }
}
```

Which returns whatever the process has after that time has elapsed. I'm gonna close this issue, but feel free to re-open it if this doesn't solve your issue.

Thanks,
-JWW
